import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import browserStructure from '../../public/htmlRenderingEngine/1-browserStructure.jpg';
import cssParsing from '../../public/cssRenderingEngine/8-cssParsing.jpg';

import styles from '../../styles/Home.module.css';

const CSSRenderingEngine: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChrisWF.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>CSS Rendering Engine</h1>
        <h3>...continued from{' '}
          <span>
            <Link href="./htmlRenderingEngine">
              HTML Rendering Engine
            </Link>
          </span>
        </h3>

        <div>
          <p>CSS parsing is more strict ( but bear in mind CSS is not truly a &quot;language&quot;, it is simply a set of markup rules.)</p>
          <Image
            src={cssParsing}
            alt="CSS Parsing"
          />
        </div>

        <p>To be continued.</p>

        <p>
          <Link href="../">Back Home.</Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered with{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default CSSRenderingEngine
