import { useEffect, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';

import styles from '@/styles/Home.module.css';
import { HL } from '@/components';

const RagExamplesForJobApplication: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChrisWF.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.articleMain}>
        <h1>{`Here are some Q&A examples we can do RAG on for easier job application form field completion.`}</h1>
        <HL />

        <article>
            <h3>{`What considerations do you make when designing and implementing a technical solution?`}</h3>
            <p>{`What is it that the end user really needs / are the product requirements clearly defined, and do they correctly align with the real needs of the platform / customer?`}</p>
            <p>{`What are the timelines, needs, contingencies, potential blockers? Let's roadmap a potential solution and estimate how much time each portion will take.`}</p>
            <p>{`Is there an existing solution which is battle-tested? Are we re-inventing the wheel? To what extend can we use proven solutions to inform the decisions we make? To what extent can we use AI to 10x our design and development process?`}</p>
            <p>{`Who are the people I need to talk to with specific expertise, eg. we need to build out a serverless function which will run on a Lambda. If not me, who is the AWS expert at the company who can review this design document and give it a thumbs up?`}</p>
        </article> 
        <HL />

        <article>
            <h3>{`What kind of problems do you most enjoy working on and why?`}</h3>
            <p>{`I consider myself a middle-of-the-stack developer. I obsess over things like performance, observability, type safety across API boundaries, developer tooling. I like "bridging the gaps" so to speak. I think this comes from a place of valuing strong technical communication and recognizing the power that a well-oiled machine (team) can have when they are strongly aligned.`}</p>
            <p>{`One idea I just had while writing this is to build a RAG pipeline that ingests answers to questions like these as documents and can generate application answers in the applicant's tone of voice. Next startup idea/project.`}</p>
            <p>{`I like stuff like the above. Building, tinkering on stuff to make users' experience and developers' experience iteratively more pleasant and more beautiful.`}</p>
        </article>
        <HL />

        <article>
            <h3>{`Describe your ideal team / working environment, what does it look like?`}</h3>
            <p>{`Smallish team, a lot of autonomy. Kind people who are willing to help and highly knowledgeable in diverse areas. Strong, clear product market fit and roadmap. I may need guidance from time to time, ie. on architectural decisions, and I recognize that this is an area for growth.`}</p>
        </article>
        <HL />

        <article>
            <h3>{`How would you describe your balance and depth between backend and frontend skills?`}</h3>
            <p>{`60/40 frontend-backend, but continuously learning across the stack. Devops novice continuously improving my skills with the help of AI. Builder, hacker, learner, community-oriented.`}</p>
        </article>

      </main>

      <footer className={styles.footer}>
        <p>
          <Link href="../">
            Home
          </Link>
        </p>
      </footer>
    </div>
  )
}

export default RagExamplesForJobApplication
