import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

const Crossword: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChrisWF.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Crosswords.
        </p>

        <p>
          <Link href="./posts/crossword/nerdingOut">
            Oct 21 2022: Nerding Out
          </Link>
        </p>

        <p>
          <Link href="./posts/crossword/bilingueTvAndFilm">
            Oct 21 2022: Bilingüe Crossword 2: TV and Film
          </Link>
        </p>

        <p>
          <Link href="./posts/crossword/crossword1">
            Oct 9 2022: Bilingüe Crossword 1: Tema Perú
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <p>
          <Link href="./">
            Home
          </Link>
        </p>
      </footer>
    </div>
  )
}

export default Crossword
