import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChrisWF.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello there.
        </h1>

        <p className={styles.description}>
          <a href="https://www.youtube.com/watch?v=KCwgpOpwixA">This is just a test.</a>
        </p>

        <p>
          <Link href="./posts/htmlRenderingEngine">
            Aug 13 2022: HTML Rendering Engine.
          </Link>
        </p>

        <p>
          <Link href="./posts/cssRenderingEngine">
            Aug 13 2022: CSS Rendering Engine. (1/2)
          </Link>
        </p>

        <p>
          <Link href="./posts/cssRenderingEngine2">
            Aug 14 2022: CSS Rendering Engine. (2/2)
          </Link>
        </p>

        <p>
          <a href="https://www.youtube.com/watch?v=0V2Mi16xd04">[EXT] Aug 15 2022: Find the Mode of a dataset (sub. Español)</a>
        </p>
      </main>

      <footer className={styles.footer}>
        <p>
          <Link href="./archive">
            Archive
          </Link>
        </p>
      </footer>
    </div>
  )
}

export default Home
