import { useEffect } from "react";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import Prism from "prismjs";
import Image from "next/image";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-tsx";

import AIdoomer from "@/public/aiTakeCodingJobs/AIdoomer.jpg";
import selectAllFilter from "@/public/aiTakeCodingJobs/selectAllFilter.jpg";

import { CodeBlock, HL } from "src/components";
import styles from "@/styles/Home.module.css";
import useWindowSize from "src/hooks/useWindowSize";
import { en } from "@/util/en";
import { es } from "@/util/es";

const chatgptfail = `
Sidenote, I found this out the other day:
ChatGPT fails miserably when trying to guess
sequences of numbers. For example, I asked it,

Given this series of numbers, what is the next
number in the list?

1, 4, 4, 7, 10, 16, ?

And it failed miserably several times,
even after I provided it with hints.

By the way, let me know in the comments
if you can solve this one.
`;

const AICodingJobs: NextPage = () => {
  const size = useWindowSize();
  const { locale } = useRouter();
  const myLang: any = locale === "en-US" ? en : es;

  useEffect(() => {
    const highlight = async () => {
      await Prism.highlightAll();
    };
    highlight();
  }, [size]);

  return (
    <div className={styles.container}>
      <Head>
        <title>ChrisWF.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.articleMain}>
        {myLang.aiTakeCodingJobs.title}
        <article style={{ maxWidth: "600px", lineHeight: "24px" }}>
          {myLang.aiTakeCodingJobs.sub1}
          {myLang.aiTakeCodingJobs[1]}
          {myLang.aiTakeCodingJobs[2]}
          {myLang.aiTakeCodingJobs[3]}
          {myLang.aiTakeCodingJobs[4]}
          {myLang.aiTakeCodingJobs[5]}
          {myLang.aiTakeCodingJobs[6]}
          {myLang.aiTakeCodingJobs[7]}
          <Image
            src={AIdoomer}
            alt="AI Doomer"
            priority
            className={styles.image}
          />
          {myLang.aiTakeCodingJobs[8]}
          {myLang.aiTakeCodingJobs[9]}
          <CodeBlock code={chatgptfail} />
          {myLang.aiTakeCodingJobs[10]}
          {myLang.aiTakeCodingJobs[11]}
          {myLang.aiTakeCodingJobs[12]}
          {myLang.aiTakeCodingJobs[13]}
          {myLang.aiTakeCodingJobs[14]}
          <Image
            src={selectAllFilter}
            alt="Custom frontend selection query language"
          />
          {myLang.aiTakeCodingJobs[15]}
          {myLang.aiTakeCodingJobs[16]}
          {myLang.aiTakeCodingJobs[17]}
          {myLang.aiTakeCodingJobs[18]}
          {myLang.aiTakeCodingJobs[19]}
          {myLang.aiTakeCodingJobs[20]}
          {myLang.aiTakeCodingJobs[21]}
          {myLang.aiTakeCodingJobs[22]}
        </article>
        <HL />
      </main>

      <footer className={styles.footer}>
        <p>
          <Link href="../">Home</Link>
        </p>
      </footer>
    </div>
  );
};

export default AICodingJobs;
