import { HL } from "@/components/HorizontalLine";

export default function DeadInternet() {
  return (
    <>
      <h1>{`Dead internet theory and enshittification`}</h1>
      <h3>{`A perspective on content recycling and meaning`}</h3>

      <HL />

      <article>
        <h3>{`Imagine, if you will, a vast library stretching as far as the eye can see.`}</h3>
        <p>{`This library is the internet. Each book represents a piece of content, each shelf a website, and each floor a different era of our digital history. Now, picture yourself walking through this library. You'll notice that many of the newest books bear striking resemblances to older books - some even re-hashing and re-espousing the same concepts as the older books nearly world for word.`}</p>
        <p>{`This image is my attempt at creating a physical representation of the dead internet theory. This is basically the idea that as we continuously reuse and regurgitate content, the internet will fill up with more and more meaningless slop. The equivalent physical representation being that our library will fill up with more and more books that are essentially just copies of older books, but maybe presented in slightly different ways. And the conclusion that many people draw from this is that by creating more and more books, and in our case, internet content, like this video, the distillation of knowledge that was contained in earlier pieces gets spread out, and watered down, and loses meaning.`}</p>
        <p>{`But let's consider for a moment what really constitutes "meaning"? Imagine we have 2 books. One is an old copy of David Hume's Dialogues, and one is a modern transcript of one of Alex O'connor's videos on the teleological argument for God, also known as the fine-tuning argument. Now, there are sections of these two which essentially reach very similar conclusions - of course with the caveat that Hume was writing in the late 18th century and his writing style reflects that, and O'connor is contemporary, and his speech patterns represent that.`}</p>
        <p>{`If both are essentially saying roughly the same things, is it fair to say that the later edition is meaningless? People who worry about the dead internet theory might say something like, well, in order to preserve a better "state" of the internet, one ought to seek out the original content. But there are 2 problems with this: One is that simply, language changes over time, and we should consider that in order for an idea to really resonate with someone, they need to understand it in terms that make sense to them. The other is that on the internet, recommendation engines like Youtube search, are far more likely to recommend you a popular recent video, than a popular video from 15 years ago. So fundamentally, even if a video is a rehashing of an older video, if it hits the viewer at just the right point in time, and gives them real knowledge at that point in time that they watch it, is that not meaningful?`}</p>
        <p>{`In the same way, if there's a useful technical blog article out there, and some AI auto generates a semantically similar blog article, and that AI blog article gets recommended to a software developer at just the right time for it to be useful to them, is that not useful? Sure, you can make an argument that maybe the original article should have appeared higher in SEO ranking or whatever, but the fact of the matter is, sometimes they do, sometimes they don't, and that's just the way things go.`}</p>
        <p>{`Similarly, I make a tiktok video about some system design thing, and I post it, and then 6 months later I repost it, I'll grant that sure, you can call this contributing to the "enshittification" of the internet. But if that video reaches at least even a small subset of new viewers the second time I post it, and it gives them value, is new knowledge gained not useful for them?`}</p>
        <p>{`So basically what I'm trying to say here is that meaning, and usefulness of information, is not solely derived from information being novel. After all, how many times do we re-read a book, or re-watch a movie, and get different insights out of it the second time around?`}</p>
        <p>{`Returning to the "library" analogy - over time, you'll notice that the positions of the books, the shelves those books are on, will shift over time. Popular books will find their way to prominent displays, while others are relegated to the back corners. In the same way, in addition to purposefully designed recommendation algorithms, the internet has a natural filtration system. Content ebbs and flows with the tides of public interest, creating a self-regulating ecosystem to some extent. For example - take AOL, once a behemoth, now sort of just a memory of early internet days (remember getting physical trial versions on a CD in the mail?) `}</p>
        <p>{`This is a crucial point - the internet naturally evolves over time; it doesn't just simply accumulate meaningless information. It's less of a static repository and more of a living, breathing entity that adapts to the changing needs of interests of its users. As the needs of the users change, content satisfying those needs will be pushed up (whether that content be old or new, original or re-hashed). Sure, dead internet theory raises valid concerns about content recycling, but kind of underestimates the power of Need x Timing. The internet - like any good library, doesn't just preserve information - it curates it, driven by collective interest.`}</p>
        <p>{`So the best way you can actively combat Dead Internet is by liking, following, commenting on the pieces of content which are genuinely useful to you at that point in time. The rest will sort itself out.`}</p>
      </article>

      <HL />
    </>
  );
}
